services:
  - type: web
    name: mtbc3-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000

  - type: web
    runtime: static
    name: mtbc3-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mtbc3-backend.onrender.com
